{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sayika",
    "module": "liveness_say",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha24"
          }
        },
        {
          "group": "id.zelory",
          "module": "compressor",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "liveness_say-2.0.aar",
          "url": "liveness_say-2.0.aar",
          "size": 77643655,
          "sha512": "655d5c0932a8c92f053f702f87b6628f9b7d0e6e58b0e664c163f8f8f3cc2a4fca1d291453d0cee89ba8d4c1f83dc109b0d22dd2bd3a6d1077ded10d5652f8f9",
          "sha256": "e2da02a56e064f1d6a3689c7307dae49abbde308cad169553a7914acc24119ca",
          "sha1": "d51fdc595197bd8109cd4eefac5d358329031be7",
          "md5": "d9bc473ba5fa3f359ecb9f601fcbe24e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha24"
          }
        },
        {
          "group": "id.zelory",
          "module": "compressor",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "SdkTest.liveness",
          "module": "openCVLibrary343",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "liveness_say-2.0.aar",
          "url": "liveness_say-2.0.aar",
          "size": 77643655,
          "sha512": "655d5c0932a8c92f053f702f87b6628f9b7d0e6e58b0e664c163f8f8f3cc2a4fca1d291453d0cee89ba8d4c1f83dc109b0d22dd2bd3a6d1077ded10d5652f8f9",
          "sha256": "e2da02a56e064f1d6a3689c7307dae49abbde308cad169553a7914acc24119ca",
          "sha1": "d51fdc595197bd8109cd4eefac5d358329031be7",
          "md5": "d9bc473ba5fa3f359ecb9f601fcbe24e"
        }
      ]
    }
  ]
}
