{
  "formatVersion": "1.1",
  "component": {
    "group": "com.sayika",
    "module": "liveness_say",
    "version": "4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha24"
          }
        },
        {
          "group": "id.zelory",
          "module": "compressor",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "liveness_say-3.0.aar",
          "url": "liveness_say-3.0.aar",
          "size": 77643655,
          "sha512": "1269189f340b3f1cd4e3eef204027d21ddb3198208b876c6f5e0c51c2c1ac1eef043255e318b260336b888493e81c1514196de56192156c750ea430e4fb3e025",
          "sha256": "99b1da23a0bade2551955f1d8cd8bcf8d2f084a98d24f3da93c49245f85596dc",
          "sha1": "826747790d2d0052f459885334c097b5d7b083ad",
          "md5": "4cd28c170f1370bc0ea004a69b00f9d9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.0.0-alpha24"
          }
        },
        {
          "group": "id.zelory",
          "module": "compressor",
          "version": {
            "requires": "3.0.1"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.10.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.0-alpha01"
          }
        }
      ],
      "files": [
        {
          "name": "liveness_say-3.0.aar",
          "url": "liveness_say-3.0.aar",
          "size": 77643655,
          "sha512": "1269189f340b3f1cd4e3eef204027d21ddb3198208b876c6f5e0c51c2c1ac1eef043255e318b260336b888493e81c1514196de56192156c750ea430e4fb3e025",
          "sha256": "99b1da23a0bade2551955f1d8cd8bcf8d2f084a98d24f3da93c49245f85596dc",
          "sha1": "826747790d2d0052f459885334c097b5d7b083ad",
          "md5": "4cd28c170f1370bc0ea004a69b00f9d9"
        }
      ]
    }
  ]
}
